version: '3'

services:
  rinha-api-01: &api
    hostname: rinha-api-01
    container_name: rinha-api-01
    build:
      context: .
      dockerfile: Dockerfile
    # tty: true

    ports:
      - "8080:8080"
    # command: /nginx/sbin/nginx -c /deploy/nginx.conf

    # volumes:
    #   - .:/api

    environment:
      HTTP_PORT: 9501
      APP_NAME: rinha_backend_2024
      APP_ENV: dev

      DB_DRIVER: pgsql
      DB_HOST: db
      DB_PORT: 5432

      DB_DATABASE: rinhadb
      DB_USERNAME: postgre
      DB_PASSWORD: postgre

    depends_on:
      - db

    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "60MB"

  rinha-api-02:
    <<: *api
    hostname: rinha-api-02
    container_name: rinha-api-02
    # tty: true

    ports:
      - "8081:8080"
    # command: /nginx/sbin/nginx -c /deploy/nginx8081.conf

    depends_on:
      - db

  db:
    hostname: db
    container_name: rinha-backend-db
    image: postgres:15.4

    environment:
      POSTGRES_DB: rinhadb
      POSTGRES_PASSWORD: postgre
      POSTGRES_USER: postgre

    # command: postgres -c config_file=/etc/postgresql/postgresql.conf
    # command: postgres -c checkpoint_timeout=600 -c max_connections=1000 -c max_wal_size=16096 -c shared_buffers=300MB -c synchronous_commit=0 -c work_mem=300MB -c fsync=0 -c full_page_writes=0
    command: 'postgres -c max_connections=300 -c shared_buffers=96MB -c checkpoint_timeout=600 -c synchronous_commit=off -c fsync=off -c full_page_writes=off -c work_mem=16MB'

    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - ./database/postgres.conf:/etc/postgresql/postgresql.conf

    ports:
      - 5432:5432

    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "370MB"

  nginx:
    image: nginx:latest
    container_name: nginx-rinha-2024
    volumes:
      - ./nginx1/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - rinha-api-01
      - rinha-api-02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: "45MB"

networks:
  default:
    driver: bridge
    name: rinha-backend-2024